apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: web-app-nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 200mi
          limits:
             cpu: 500m
             memory: 500mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 10
        readinessProbe:
           tcpSocket:
           port: 80

          

